name: greeting

on: 
  push:
    branches: ['main']
    paths: ['.github/workflows/*']
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3

      - name: "Install Dependencies"
        run: npm install

      - name: "Lint Code"
        run: npm run lint

      - name: "Run Script"
        run: |
          echo "Running script..."
          echo "Script finished."
