name: greeting

on: 
  push:
    branches: ['main']
    paths: ['.github/workflows/*']

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  greeting:
    runs-on: ubuntu-latest
    env:
      MESSAGE: "Déploiement réussi"

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3

      - name: "Hello World"
        run: echo "Hello World"

      - name: "Handle Pull Request"
        if: github.event_name == 'pull_request'
        run: echo "Pull request event detected"

      - name: "Handle Push"
        if: github.event_name == 'push'
        run: echo "Push event detected"

      - name: "Install Dependencies"
        run: npm install

      - name: "Run Lint (Optional)"
        run: |
          if [ -f "package.json" ]; then
            npm run lint || echo "No linting required"
          else
            echo "Skipping lint step: package.json not found"
          fi

      - name: "Display MESSAGE"
        run: echo "$MESSAGE"

      - name: "Use Secret API_KEY"
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo "API Key is: $API_KEY"

          - name: "Generate Report"
          run: echo "Rapport d'analyse" > report.txt
  
      - name: "Upload Artifact: Report"
        uses: actions/upload-artifact@v3
        with:
            name: report
            path: report.txt