name: greeting

on: 
  push:
    branches: ['main']
    paths: ['.github/workflows/*']

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  greeting:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3

      - name: "Hello World"
        run: echo "Hello World"

      - name: "Install Dependencies"
        run: npm install

      - name: "Run Lint (Optional)"
        run: |
          if [ -f "package.json" ]; then
            npm run lint || echo "No linting required"
          else
            echo "Skipping lint step: package.json not found"
          fi
